# Generated by Django 4.2 on 2024-01-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_rename_tag_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
