# Generated by Django 4.2 on 2024-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_rename_name_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
